spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##dev
    password: c##dev
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  cloud:
    stream:
      bindings:
        kafka:
          binder: 
            zkNodes: localhost
            brokers: localhost
        output:
          destination: my-replicated-topic
          content-type: application/json


      
server:
  port: 8080
  context-path: /api